//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <stdio.h>

#define MAXFIB 4000000

int main(int argc, char * * argv)
{
  int flag = 0;
  int a = 1;
  int b = 1;
  int sum = 0;
  int curr = 0;
  while(a < MAXFIB && b < MAXFIB) {
    if(flag == 0) {
      flag = 1;
      a += b;
      curr = a;
    }
    else {
      flag = 0;
      b += a;
      curr = b;
    }
    if(curr % 2 == 0)
      sum += curr;
  }
  
  printf("Sum of all even-values Fibonacci terms under %d: %d\n", MAXFIB, sum);

  return sum;
}
